Client {
    org.apache.zookeeper.server.auth.DigestLoginModule required
    username="kafka1"
    password="kafka1-secret";
};

KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="admin"
    password="admin-secret"
    user_admin="admin-secret"
    user_producer="producer-secret"
    user_consumer="consumer-secret";
};
